# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3eacca06d1957ed79566a44efa601ad0225b56df8ebba6376c716cf31e47bddd9e0bd35d94105256bfa4c51f0576a54fc51f70bdc90cf3fdec3f763448c9471c

test:
  secret_key_base: 3c3bc93e52db5e839cc64c5c25f1a8a77f3a792b535f8db1869e3fa3c2421024042567863e80d08d29db6656aa6f88b97ab12bec9c844569e3f5c8a1752cb86e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
